SPRITE_SIDE = 50
SPRITE_NUM = 15
BOARD_SIDE = SPRITE_NUM * SPRITE_SIDE
ITEMS_SIZE = (SPRITE_SIDE, BOARD_SIDE)
SCREEN_SIZE = (BOARD_SIDE + ITEMS_SIZE[0], BOARD_SIDE)

CAPTION = "MacGyver"

WALL = 0
GROUND = 1
MACGYVER = 2
GUARDIAN = 3
SYRINGE = 0
ETHER = 1
TUBE = 2